### ISSUE TITLE
Общие вопросы по проекту + маленькая правка в Readme

### ISSUE THREAD

**Issue by amarkhai** [profi-tech/tsqm-php#20]
Хай!
Прочитал на хабре статью https://habr.com/ru/articles/776794/
решил поразбираться, как это работает

Я понимаю, что это не для использования в проде и не знаю, есть ли какие-то планы на развитие этого репозитория, но тем не менее хотел уточнить пару моментов:
 - в readme указано .env.example, а в проекте - env-example. Мелочь, но все таки)
 - Правильно ли я понимаю, что разработчики, которые этим пользуется, должны описывать шаги в своих тасках через генераторы (использую конструкции типа ```$valid = yield $this->validatorTasks->validateName($name); ```)? Это кажется неудобным, тк какими-то интерфейсами это не опишешь, легко можно проглядеть на код ревью
 - В работу можно только одну задачу отправить? Несмотря на название, TsqmTasks принимает только один аргумент в конструкторе
 - ```$reverter->revert(...)``` убрали, а как теперь выполняется откат транзакции, если, например, закончились ретраи?
 
 Сорри, что пишу все это в issue, комменты к статье оставлять не могу, тк "Вы можете оставлять комментарии только к свежим публикациям"

**Comment by em1nx** [comment]
> Это кажется неудобным, тк какими-то интерфейсами это не опишешь, легко можно проглядеть на код ревью
@amarkhai не очень понял что ты имеешь ввиду :)

**Comment by em1nx** [comment]
> $reverter->revert(...) убрали, а как теперь выполняется откат транзакции, если, например, закончились ретраи?

Все логику откатов нужно прописывать вручную и в явном виде в том месте, где по твоей логике должен случиться откат.

**Comment by em1nx** [comment]
> в readme указано .env.example, а в проекте - env-example. Мелочь, но все таки)
Поправлю, спасибо )

**Comment by em1nx** [comment]
> Я понимаю, что это не для использования в проде и не знаю, есть ли какие-то планы на развитие этого репозитория

Вот как раз вернулся к этой истории — буду пробовать затаскивать в прод.
